# Generated by Django 4.0.5 on 2022-06-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('offer', 'OFFER'), ('category', 'CATEGORY')], max_length=21)),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('parentId', models.UUIDField(null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.item')),
            ],
        ),
    ]
